name: build_master

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.2
    - name: Build with Gradle
      run: ./gradlew build
